type: perceiver

unet:
  image_size: 32          # Input image resolution
  dim: 32                 # Input token dim (used for PerceiverIO input & query dim)
  latent_dim: 512         # Latent representation dimension
  num_latents: 64         # Number of latent vectors
  depth: 6                # Number of self-attention blocks
  logits_dim: 3072        # Output flattened image: 3 x 32 x 32

ddim:
  0:
    ddim_sampling_steps: 20
    calculate_fid: true
    num_fid_sample: 6000
    generate_image: true

inferencer:
  dataset: cifar10
  batch_size: 128
  clip: true
  num_samples_per_image: 64
  num_images_to_generate: 10
  ddpm_fid_estimate: true
  ddpm_num_fid_samples: 60000
  return_all_step: true
  make_denoising_gif: true
  num_gif: 50
