type: original
unet:
  dim: 64
  image_size: 32
  dim_multiply:
  - 1
  - 2
  - 2
  - 2
  attn_resolutions:
  - 16
  dropout: 0.1
  num_res_blocks: 2
ddim:
  0:
    ddim_sampling_steps: 10
    calculate_fid: false
    num_fid_sample: 100
    generate_image: true
inferencer:
  dataset: cifar10
  batch_size: 8
  clip: true
  num_samples_per_image: 16
  num_images_to_generate: 5
  ddpm_fid_estimate: false
  ddpm_num_fid_samples: 100
  return_all_step: true
  make_denoising_gif: true
  num_gif: 30